[package]
name = "nrf-usbd-example"
version = "0.1.0"
edition = "2018"
publish = false

[features]
default = [
    "defmt-default",
]
defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []

[dependencies]
panic-probe = { version = "0.3.0", features = ["print-defmt"] }
defmt = "0.3.0"
defmt-rtt = "0.3.1"

cortex-m = "0.7.3"
cortex-m-rt = "0.7.1"

nrf-usbd = { path = "../" }
usb-device = "0.2.7"
usbd-serial = "0.1.0"
nrf52840-pac = "0.10.1"

[patch.crates-io]
usb-device = { path = "../usb-device" }
usbd-serial = { path = "../usbd-serial" }